unit TestAtributoLength;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Generics.Collections, Classes, Contnrs, UStringr, RegExpr;

type
  // Test methods for class TAtributoLength

  TestTAtributoLength = class(TTestCase)
  strict private
    FAtributoLength: TAtributoLength;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestTransformarStringMaiorQueLength;
    procedure TestTransformarStringMenorQueLength;
    procedure TestTransformarStringIgualALength;
  end;

implementation

procedure TestTAtributoLength.SetUp;
begin
  FAtributoLength := TAtributoLength.Create;
end;

procedure TestTAtributoLength.TearDown;
begin
  FAtributoLength.Free;
  FAtributoLength := nil;
end;

procedure TestTAtributoLength.TestTransformarStringIgualALength;
var
  Valor: WideString;
begin
  FAtributoLength.Valor := 5;
  Valor := FAtributoLength.Transformar('12345');
  CheckEqualsWideString('12345', Valor);
end;

procedure TestTAtributoLength.TestTransformarStringMaiorQueLength;
var
  Valor: WideString;
begin
  FAtributoLength.Valor := 3;
  Valor := FAtributoLength.Transformar('12345');
  CheckEqualsWideString('123', Valor);
end;

procedure TestTAtributoLength.TestTransformarStringMenorQueLength;
var
  Valor: WideString;
begin
  FAtributoLength.Valor := 10;
  Valor := FAtributoLength.Transformar('12345');
  CheckEqualsWideString('12345' + StringOfChar(' ', 5), Valor);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAtributoLength.Suite);
end.

