unit TestStringr;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UStringr, UDefaultParser;

type
  // Test methods for class TStringr

  TestTStringr = class(TTestCase)
  strict private
    FStringr: TStringr;
    FParser: TDefaultParser;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestParserNaoPodeSerNulo;
    procedure TestParametroSemRepeticao;
    procedure TestParametroComRepeticao;
    procedure TestDataSemFormato;
    procedure TestDataComFormato;
    procedure TestHoraSemFormato;
    procedure TestHoraComFormato;
    procedure TestDataHora;
    procedure TestUpperCase;
    procedure TestLowerCase;
    procedure TestStringMaiorQueLength;
    procedure TestStringMenorQueLength;
    procedure TestCaracterEscape;
  end;

implementation

uses
  SysUtils;

procedure TestTStringr.SetUp;
begin
  FParser := TDefaultParser.Create;
end;

procedure TestTStringr.TearDown;
begin
//  FParser.Free;
end;

procedure TestTStringr.TestHoraComFormato;
var
  ReturnValue: string;
  Formato: string;
begin
  Formato := 'h "h" m "m" s "s"';
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := '{Time format=''' + Formato + '''}';
  ReturnValue := FStringr.ToString;
  CheckEquals(FormatDateTime(Formato, Time), ReturnValue);
end;

procedure TestTStringr.TestParserNaoPodeSerNulo;
begin
  ExpectedException := ETemplateError;
  FStringr := TStringr.Create(nil);
end;

procedure TestTStringr.TestHoraSemFormato;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := '{Time}';
  ReturnValue := FStringr.ToString;
  CheckEquals(TimeToStr(Time), ReturnValue);
end;

procedure TestTStringr.TestLowerCase;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := 'Hello, {name case=lower}!';
  FStringr['name'] := 'WORLD';
  ReturnValue := FStringr.ToString;
  CheckEquals('Hello, world!', ReturnValue);
end;

procedure TestTStringr.TestCaracterEscape;
var
  ReturnValue: string;
  FormatoOriginal, FormatoEquivalente: string;
begin
  FormatoOriginal := 'dd \''de\'' mmmm \''de\'' yyyy';
  FormatoEquivalente := 'dd ''de'' mmmm ''de'' yyyy';
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := '{Date format=''' + FormatoOriginal + '''}';
  ReturnValue := FStringr.ToString;
  CheckEquals(FormatDateTime(FormatoEquivalente, Date), ReturnValue);
end;

procedure TestTStringr.TestDataComFormato;
var
  ReturnValue: string;
  Formato: string;
begin
  Formato := 'dd mm yyyy';
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := '{Date format=''' + Formato + '''}';
  ReturnValue := FStringr.ToString;
  CheckEquals(FormatDateTime(Formato, Date), ReturnValue);
end;

procedure TestTStringr.TestDataSemFormato;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := '{Date}';
  ReturnValue := FStringr.ToString;
  CheckEquals(DateToStr(Date), ReturnValue);
end;

procedure TestTStringr.TestDataHora;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := '{DateTime}';
  ReturnValue := FStringr.ToString;
  CheckEquals(DateTimeToStr(Now), ReturnValue);
end;

procedure TestTStringr.TestParametroComRepeticao;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := 'Hello, {name}! How are you, {name}?';
  FStringr['name'] := 'world';
  ReturnValue := FStringr.ToString;
  CheckEquals('Hello, world! How are you, world?', ReturnValue);
end;

procedure TestTStringr.TestParametroSemRepeticao;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := 'Hello, {name}!';
  FStringr['name'] := 'world';
  ReturnValue := FStringr.ToString;
  CheckEquals('Hello, world!', ReturnValue);
end;

procedure TestTStringr.TestUpperCase;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := 'Hello, {name case=upper}!';
  FStringr['name'] := 'world';
  ReturnValue := FStringr.ToString;
  CheckEquals('Hello, WORLD!', ReturnValue);
end;

procedure TestTStringr.TestStringMaiorQueLength;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := 'Hello, {name length=3}!';
  FStringr['name'] := 'world';
  ReturnValue := FStringr.ToString;
  CheckEquals('Hello, wor!', ReturnValue);
end;

procedure TestTStringr.TestStringMenorQueLength;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create(FParser);
  FStringr.Texto := 'Hello, {name length=10}!';
  FStringr['name'] := 'world';
  ReturnValue := FStringr.ToString;
  CheckEquals('Hello, world     !', ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTStringr.Suite);
end.

