unit TestUStringr;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UStringr;

type
  // Test methods for class TStringr

  TestTStringr = class(TTestCase)
  strict private
    FStringr: TStringr;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestParametroSemRepeticao;
    procedure TestParametroComRepeticao;
    procedure TestDataSemFormato;
    procedure TestDataComFormato;
    procedure HoraSemFormato;
    procedure HoraComFormato;
    //Maiúsculas
    //Minúsculas
    //Size
    //atributos com aspas
    //caracteres de escape \'
  end;

implementation

uses
  SysUtils;

procedure TestTStringr.HoraComFormato;
var
  ReturnValue: string;
  Formato: string;
begin
  Formato := 'h "h" m "m" s "s"';
  FStringr := TStringr.Create('{Time format=''' + Formato + '''}');
  ReturnValue := FStringr.Render;
  CheckEquals(FormatDateTime(Formato, Time), ReturnValue);
end;

procedure TestTStringr.HoraSemFormato;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create('{Time}');
  ReturnValue := FStringr.Render;
  CheckEquals(TimeToStr(Time), ReturnValue);
end;

procedure TestTStringr.SetUp;
begin
end;

procedure TestTStringr.TearDown;
begin
end;

procedure TestTStringr.TestDataComFormato;
var
  ReturnValue: string;
  Formato: string;
begin
  Formato := 'dd-mm-yyyy';
  FStringr := TStringr.Create('{Date format=' + Formato + '}');
//  FStringr := TStringr.Create('Hoje é {date:dddd, d "de" mmmm "do ano de" yyyy}');
  ReturnValue := FStringr.Render;
  CheckEquals(FormatDateTime(Formato, Date), ReturnValue);
end;

procedure TestTStringr.TestDataSemFormato;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create('{Date}');
  ReturnValue := FStringr.Render;
  CheckEquals(DateToStr(Date), ReturnValue);
end;

procedure TestTStringr.TestParametroComRepeticao;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create('Hello, {name}! How are you, {name}?');
  FStringr['name'] := 'world';
  ReturnValue := FStringr.Render;
  CheckEquals('Hello, world! How are you, world?', ReturnValue);
end;

procedure TestTStringr.TestParametroSemRepeticao;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create('Hello, {name}!');
  FStringr['name'] := 'world';
  ReturnValue := FStringr.Render;
  CheckEquals('Hello, world!', ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTStringr.Suite);
end.

