unit TestUStringr;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UStringr;

type
  // Test methods for class TStringr

  TestTStringr = class(TTestCase)
  strict private
    FStringr: TStringr;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestParametroSemRepeticao;
    procedure TestParametroComRepeticao;
  end;

implementation

procedure TestTStringr.SetUp;
begin
end;

procedure TestTStringr.TearDown;
begin
end;

procedure TestTStringr.TestParametroComRepeticao;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create('Hello, {name}! How are you, {name}?');
  FStringr['name'] := 'world';
  ReturnValue := FStringr.Render;
  CheckEquals('Hello, world! How are you, world?', ReturnValue);
end;

procedure TestTStringr.TestParametroSemRepeticao;
var
  ReturnValue: string;
begin
  FStringr := TStringr.Create('Hello, {name}!');
  FStringr['name'] := 'world';
  ReturnValue := FStringr.Render;
  CheckEquals('Hello, world!', ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTStringr.Suite);
end.

